frontend:
  themes: !include themes.yaml

homeassistant:
  customize: !include customize.yaml

discovery:

circadian_lighting:
nordpool:

homekit:
  pincode: 220-97-419

default_config:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Text to speech
tts:
  - platform: google_translate

auto_backup:
  auto_purge: true

#tradfri:
#  host: 192.168.1.15
#  allow_tradfri_groups: true

hue:
  bridges:
    - host: 192.168.1.150
      allow_unreachable: true
      allow_hue_groups: true

hacs:
  token: !secret hacs_token
  appdaemon: true
  python_script: True
  theme: True

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

media_player:
  - platform: bluesound
    hosts:
      - host: 192.168.1.150
        name: Køkken Radio
        port: 11000

device_tracker:
  - platform: iphonedetect
    consider_home: 60
    interval_seconds: 2
    hosts:
      Rut: 192.168.1.200
      Casper: 192.168.1.205
      Cristian: 192.168.1.210
      Frederrikke: 192.168.1.215

fan:
  - platform: mqtt
    name: "Baggang-fan"
    state_topic: "stat/baggang-Temperature-Humidity/POWER"
    command_topic: "cmnd/baggang-Temperature-Humidity/power"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

sensor:
  - platform: mqtt
    state_topic: "tele/Cristian_light-ps4controller/SENSOR"
    name: "Cristian-Temperature"
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    value_template: "{{ value_json.DHT11.Temperature }}"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "tele/Cristian_light-ps4controller/SENSOR"
    name: "Cristian-Humidity"
    icon: 'mdi:water-percent'
    value_template: "{{ value_json.DHT11.Humidity }}"
    unit_of_measurement: '%'
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "tele/baggang-Temperature-Humidity/SENSOR"
    name: "baggang-Temperature"
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    value_template: "{{ value_json.AM2301.Temperature }}"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "tele/baggang-Temperature-Humidity/SENSOR"
    name: "baggang-Humidity"
    icon: 'mdi:water-percent'
    value_template: "{{ value_json.AM2301.Humidity }}"
    unit_of_measurement: '%'
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: nordpool
    region: "DK1" # This can be skipped if you want Kr.sand

light:
  - platform: mqtt
    name: "SW_kitchen-uplight"
    command_topic: "cmnd/SW_kitchen-uplight/power"
    state_topic: "stat/SW_kitchen-uplight/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Cristian_light-ps4controller"
    command_topic: "cmnd/Cristian_light-ps4controller/power"
    state_topic: "stat/Cristian_light-ps4controller/POWER"
    rgb_state_topic: "stat/Cristian_light-ps4controller/color"
    rgb_command_topic: "cmnd/Cristian_light-ps4controller/color"
    brightness_state_topic: "stat/Cristian_light-ps4controller/dimmer"
    brightness_command_topic: "cmnd/Cristian_light-ps4controller/dimmer"
    brightness_value_template: "{{ value_json.Dimmer }}"
    brightness_scale: 100
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

switch:
  - platform: circadian_lighting
    lights_ct:
      - light.tradfri_bulb_6_2
