#
# Turn kitchen uplight off for the night at 
#

id: '1578155764412'
alias: kitchen_uplight_off_for_night
trigger:
- platform: time
  at: 00:30:00
condition: []
action:
- entity_id: light.sw_kitchen_uplight
  service: light.turn_off