# Sensprs #

sensor:
  - platform: mqtt
    state_topic: "tele/Cristian_light-ps4controller/SENSOR"
    name: "Cristian-Temperature"
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    value_template: "{{ value_json.DHT11.Temperature }}"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "tele/Cristian_light-ps4controller/SENSOR"
    name: "Cristian-Humidity"
    icon: 'mdi:water-percent'
    value_template: "{{ value_json.DHT11.Humidity }}"
    unit_of_measurement: '%'
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "tele/baggang-Temperature-Humidity/SENSOR"
    name: "baggang-Temperature"
    icon: 'mdi:thermometer'
    unit_of_measurement: '°C'
    value_template: "{{ value_json.AM2301.Temperature }}"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "tele/baggang-Temperature-Humidity/SENSOR"
    name: "baggang-Humidity"
    icon: 'mdi:water-percent'
    value_template: "{{ value_json.AM2301.Humidity }}"
    unit_of_measurement: '%'
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: nordpool
    region: "DK1" # This can be skipped if you want Kr.sand
