#
# Turn light in corridor on 1h30m after sunset at 95% and kelvin 3700
#

id: '1580043131735'
alias: corridor_uplight_on_95_after_sunset
trigger:
- platform: sun
  event: sunset
  offset: 01:30:00
condition:
  condition: time
  after: '15:00:00'
  before: '23:30:00'
action:
  service: light.turn_on
  data:
    entity_id: light.wled
    brightness_pct: 95
    kelvin: 3700